Region.create!([
  {name: "chicagoland", image_url: "https://chicagoagentmagazine.com/wp-content/uploads/2016/10/chicago-chicagoland-area-metro-skyline-homes-housing-market.jpg", begDate: "2015-09-08", endDate: "2017-08-31", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: "Pursuing a Master's Degree in Anthropology led me here.  "},
  {name: "roadtrip 2016", image_url: "http://www.visitsmokies.org/wp-content/uploads/2016/07/Nantahala-Lake.jpg?x73979", begDate: "2016-08-14", endDate: "2016-08-21", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: "My good friend Walter and I hopped into his Ford Mustang for some classic fun on the road in four South-Midwestern States."},
  {name: "europe", image_url: "https://michaellanglois.fr/medias/blick-auf-den-berliner-dom-the-westin-grand-hotel-berlin.jpg", begDate: "2017-10-21", endDate: "2017-11-24", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: "Two trips were made, each including 5+ countries.  One trip was in 2014 with two good friends, and another in 2017 by myself.  "},
  {name: "toronto", image_url: "http://3.bp.blogspot.com/-z6xWC_kQBmQ/UZ0rv2jPPoI/AAAAAAAAAAA/lyiSNkQw9M4/s400/summernight8-backalleys-cho.jpg", begDate: "1992-11-13", endDate: nil, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: "Where I was born and raised.  Several geography-related school projects, plus my love for biking, have taken me all around the place.  "},
  {name: "gatineau", image_url: "http://farm1.staticflickr.com/82/270731190_831f5426a7_z.jpg?zz=1", begDate: "9998-09-09", endDate: "2018-11-04", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: "Many summers were spent here at a cottage belonging to family friends."},
  {name: "eastern canada", image_url: "https://s3-us-west-2.amazonaws.com/oneoceanexpeditions/itineraries/canadas-east-coast/gallery/canadas-east-coast3.jpg", begDate: "2006-07-15", endDate: "2006-08-15", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: "A long family road trip, broken by ferry rides, took us from the Gulf of the St. Lawrence to the swamps of Labrador"},
  {name: "northwest ontario", image_url: "http://1.bp.blogspot.com/-Bkt2WwZN2YY/U49Rt7Nt93I/AAAAAAAABaQ/QnTiHRQyAUM/s1600/DSC04680+(2)small.jpg", begDate: "2004-07-01", endDate: "2004-07-15", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: "The road to Quetico Provincial Park from Toronto took us along the Great Lakes via the TransCanada Highway.  Before getting there, we stopped at other parks and small towns."}
  {name: "TESTING", image_url: "http://images.carsondellosa.com/media/cd/images/product/large/188028.jpg", begDate: "2004-07-01", endDate: "2004-07-15", image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, description: "The road to Quetico Provincial Park from Toronto took us along the Great Lakes via the TransCanada Highway.  Before getting there, we stopped at other parks and small towns."}

])

Location.create!([
  {caption: "BIG & Little's", region_name: "Chicagoland", image_url: "http://checkplease.wttw.com/sites/default/files/cp_bigandlittles.jpg", date: "2016-10-01", nearest_area: "Chicago", region_id: 3},
  {caption: "Smartbar", region_name: "chicagoland", image_url: "http://www.6am-group.com/wp-content/uploads/2017/03/smartbar-queen-1030x644.jpg", date: "2015-11-30", nearest_area: "Wrigleyville", region_id: 3},
  {caption: "Beaubien Forest Preserve", region_name: "chicagoland", image_url: "http://fpdcc.com/wp-content/uploads/2018/02/Beaubien-1_6_18_Laura-Milkert.jpg", date: "2016-01-16", nearest_area: "Altgeld, S Chicago ", region_id: 3},
  {caption: "Lake Calumet", region_name: "chicagoland", image_url: "https://render.fineartamerica.com/images/images-profile-flow/350/images/artworkimages/medium/1/sunset-on-lake-calumet-with-the-bradshaw-mckee-christine-douglas.jpg", date: "2015-11-14", nearest_area: "Pullman, S Chicago", region_id: 3},
  {caption: "Landfill Remediation Project", region_name: "chicagoland", image_url: "https://dynamicmedia.zuza.com/zz/m/original_/0/3/032832d4-ded0-4328-96c9-b1509a7e135c/WE_DEC15_atlas_landfill____Super_Portrait.jpg", date: "2015-11-14", nearest_area: "Lake Calumet", region_id: 3},
  {caption: "U.S Steel - South Works", region_name: "Chicagoland", image_url: "https://farm8.staticflickr.com/7718/16606251793_c8860f6569_b.jpg", date: "2015-11-14", nearest_area: "Calumet River, S Chicago", region_id: 3},
  {caption: "Calumet Fisheries", region_name: "chicagoland", image_url: "http://makeitbetter.net/wp-content/uploads/2018/02/Calumet-Fisheries-sign.jpg", date: "2017-01-08", nearest_area: "Chicago Skyway ", region_id: 3},
  {caption: "Louisville, KY", region_name: "Roadtrip 2016", image_url: "http://greatruns.com/wp-content/uploads/2017/09/Waterfront-Park-700x349.jpg", date: "2016-08-14", nearest_area: "", region_id: 4},
  {caption: "Woodford Reserve Distillery", region_name: "Roadtrip 2016", image_url: "https://media.woodfordreserve.com/wp-content/uploads/2017/03/19162901/WR_Warehouse_Bourbon_New_Bottle_Horz_cropped.jpg", date: "2016-08-15", nearest_area: "Versailles, KY", region_id: 4},
  {caption: "Buffalo Trace Distillery", region_name: "Roadtrip 2016", image_url: "https://www.buffalotracedistillery.com/sites/default/files/styles/fullsize/public/Distillery%20Grounds.jpg?itok=HEAoJv9z", date: "2016-08-15", nearest_area: "Frankfort, KY", region_id: 4},
  {caption: "Pigeon Forge, TN", region_name: "Roadtrip 2016", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Hatfield_%26_McCoy_Dinner_Show%2C_Pigeon_Forge%2C_TN_IMG_5042.JPG/1280px-Hatfield_%26_McCoy_Dinner_Show%2C_Pigeon_Forge%2C_TN_IMG_5042.JPG", date: "2016-08-16", nearest_area: "", region_id: 4},
  {caption: "Three Bears Store", region_name: "Roadtrip 2016", image_url: "https://smokymountains.com/wp-content/uploads/2014/04/5E0A0396.jpg", date: "2016-08-16", nearest_area: "Pigeon Forge, TN", region_id: 4},
  {caption: "Great Smoky Mountains National Park", region_name: "Roadtrip 2016", image_url: "https://thumbnails.trvl-media.com/U6Zo6Wn0_4i6vbNIcSe1IIpGvV0=/768x432/images.trvl-media.com/media/content/shared/images/travelguides/destination/6025878/Great-Smoky-Mountains-National-Park-And-Vicinity-59212.jpg", date: "2016-08-16", nearest_area: "Tennessee and North Carolina", region_id: 4},
  {caption: "Shooter's Guns Ammo and Range", region_name: "Roadtrip 2016", image_url: "https://s3-media4.fl.yelpcdn.com/bphoto/xuZ4oElrbjfqUWMIrMsUOQ/348s.jpg", date: "2016-08-18", nearest_area: "Nashville, TN", region_id: 4},
  {caption: "Prince's Hot Chicken ", region_name: "Roadtrip 2016", image_url: "http://theeatenpath.com/wordpress/wp-content/uploads/2010/11/princes-hot-chicken-half-chicken-medium-nashville-tn_01.jpg", date: "2016-08-18", nearest_area: "Nashville, TN", region_id: 4},
  {caption: "Monell's Dining and Catering", region_name: "Roadtrip 2016", image_url: "https://monellstn.com/wp-content/uploads/2016/08/Monells-Dining-and-Catering-top-rated-restaurantin-Nashville-TN.jpg", date: "2016-08-19", nearest_area: "Nashville, TN", region_id: 4},
  {caption: "Bonerville ", region_name: "Roadtrip 2016", image_url: "https://i.ytimg.com/vi/6udIQcpZ3mc/maxresdefault.jpg", date: "2016-08-19", nearest_area: "St. Louis", region_id: 4},
  {caption: "St. Louis City Museum", region_name: "Roadtrip 2016", image_url: "https://inhabitat.com/wp-content/blogs.dir/1/files/2011/05/st-louis-city-museum.jpg", date: "2016-08-20", nearest_area: "St. Louis, MO", region_id: 4},
  {caption: "Cementland", region_name: "Roadtrip 2016", image_url: "https://nextstl.com/wp-content/uploads/Cementland_21-1024x683.jpg", date: "2016-08-21", nearest_area: "NW St. Louis", region_id: 4}
])
